FreelanceService/Controllers/ExecutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FreelanceService.BLL.DTO;
using FreelanceService.BLL.Interfaces;
using FreelanceService.Common.Enum;
using FreelanceService.Web.Models;
using FreelanceService.Web.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FreelanceService.Web.Controllers
{
    public class ExecutorController : Controller
    {
        IUserService _userService;
        IJobService _jobService;
        IResponseService _responseService;
        ICategoryService _categoryService;
        IMapper _mapper;


        IViewModelValidationService _validationService;

        /// <summary>
        /// Dependency Injection for jobService and userService
        /// </summary>
        /// <param name="jobService"></param>
        /// <param name="userService"></param>
        public ExecutorController(
            IJobService jobService,
            IUserService userService,
            IViewModelValidationService validationService,
            IResponseService responseService,
            IMapper mapper,
            ICategoryService categoryService)
        {
            _jobService = jobService;
            _userService = userService;
            _validationService = validationService;
            _responseService = responseService;
            _mapper = mapper;
            _categoryService = categoryService;
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> MyResponses()
        {
            var user = await _userService.FindUserByEmail(User.Identity.Name);
            var responsesOfExecutor = await _responseService.FindResponseByUserExecutorId(user.Id);
            var mapResponseOfExecutor = _mapper.Map<IEnumerable<ResponseDTO>, IEnumerable<ResponseListOfExecutors>>(responsesOfExecutor);
            return View(mapResponseOfExecutor);
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> ResponseDetails(int responseId)
        {
            var responseOfExecutor = await _responseService.FindResponseById(responseId);
            var mapResponseDetails = _mapper.Map<ResponseDTO, ResponseDetailsViewModel>(responseOfExecutor);
            var job = await _jobService.FindJobById(mapResponseDetails.JobId);
            mapResponseDetails.CategoryId = job.CategoryId;
            var categoryDto = await _categoryService.FindCategoryById(mapResponseDetails.CategoryId);
           
            mapResponseDetails.CategoryName = categoryDto.Name;
            mapResponseDetails.StatusJob = job.Status;
            return View(mapResponseDetails);
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<ViewResult> EditResponse(int responseId)
        {
            var job = await _responseService.FindResponseById(responseId);
            var mapJob = _mapper.Map<ResponseDTO, ResponseEditViewModel>(job);
            return View(mapJob);
        }

        [HttpPost]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> EditResponse(ResponseEditViewModel model)
        {
            var responseDTO = await _responseService.FindResponseById(model.Id);
            var mapJob = _mapper.Map<ResponseEditViewModel, ResponseDTO>(model);
            responseDTO.Price = mapJob.Price; //вынести на bll
            responseDTO.Description = mapJob.Description;
            await _responseService.Update(responseDTO);

            return RedirectToAction("MyResponses");
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> SendForVerification(int jobId)
        {
            return View(jobId);
        }

        [HttpPost]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> ConfirmSendForVerification(int jobId)
        {
            var statusCode = (int)JobStatusEnum.WaitingForConfirmation;
            await _jobService.UpdateStatusJob(jobId, statusCode);
            return RedirectToAction("MyResponses");
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> CancelResponse(int jobId)
        {
            var user = await _userService.FindUserByEmail(User.Identity.Name);  //перенести логику в responsesrvice
            var response = await _responseService.FindResponseByIdExecutorAndJobId(user.Id, jobId);
            await _responseService.Remove(response.Id);
            return RedirectToAction("MyResponses");
        }
    }
}

FreelanceService/Controllers/HomeController.cs
using AutoMapper;
using FreelanceService.BLL.DTO;
using FreelanceService.BLL.Interfaces;
using FreelanceService.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FreelanceService.Web.Controllers
{
    /// <summary>
    /// Display all jobs in system
    /// </summary>
    public class HomeController : Controller
    {

        IUserService _userService;
        IJobService _jobService;
        IMapper _mapper;
        ICategoryService _categoryService;
        public HomeController(IJobService jobService, 
            IUserService userService, 
            IMapper mapper,
            ICategoryService categoryService)
        {
            _jobService = jobService;
            _userService = userService;
            _mapper = mapper;
            _categoryService = categoryService;
        }


        [Authorize(Roles = "Исполнитель,Заказчик")]
        public async Task<ActionResult> Executors(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            int pageSize = 3;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["RatingSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Rating_desc" : "";
            ViewData["RegistrationDateTimeSortParm"] = sortOrder == "RegistrationDateTime" ? "RegistrationDateTime_desc" : "RegistrationDateTime";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;
            ViewData["CurrentFilter"] = searchString;

            var list = await _userService.GetAllSorting(sortOrder);
            var search = await _userService.Search(searchString, list);
            var mapAllExecutor = _mapper.Map<IEnumerable<UserDTO>, IEnumerable<UserExecutorViewModel>>(search);
            var view = PaginatedListModel<UserExecutorViewModel>.Create(mapAllExecutor.AsQueryable(), pageNumber ?? 1, pageSize);
            return View(view);
        }


        /// <summary>
        /// View all jobs
        /// </summary>
        /// <returns>View Home/Index</returns>
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {

            int pageSize = 3;

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "Price_desc" : "Price";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;
            ViewData["CurrentFilter"] = searchString;

            var list = await _jobService.GetAllSorting(sortOrder);
            var search = _jobService.Search(searchString, list);
            var mapJobView = _mapper.Map<IEnumerable<JobDTO>, IEnumerable<JobViewModel>>(search);
            foreach (var item in mapJobView)
            {
                var categoryDto = await _categoryService.FindCategoryById(item.CategoryId);
                item.CategoryName = categoryDto.Name;
            }
            var view = PaginatedListModel<JobViewModel>.Create(mapJobView.AsQueryable(), pageNumber ?? 1, pageSize);
            return View(view);

        }
    }
}

FreelanceService/Controllers/ProfileController.cs
using AutoMapper;
using FreelanceService.BLL.DTO;
using FreelanceService.BLL.Interfaces;
using FreelanceService.BLL.Interfaces.ValidationServices;
using FreelanceService.Common.Enum;
using FreelanceService.Common.Extensions;
using FreelanceService.Common.Helpers;
using FreelanceService.Web.Models;
using FreelanceService.Web.Validation;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;


namespace FreelanceService.Web.Controllers
{
    /// <summary>
    /// Сontroller is responsible for displaying profile information, profile edit, adding new jobs by the customer
    /// </summary>
    public class ProfileController : Controller
    {
        IUserService _userService;
        IJobService _jobService;
        IMapper _mapper;
        IValidaterUser _validateUser;

        IViewModelValidationService _validationService;

        /// <summary>
        /// Dependency Injection for jobService and userService
        /// </summary>
        /// <param name="jobService"></param>
        /// <param name="userService"></param>
        public ProfileController(
            IJobService jobService,
            IUserService userService,
            IViewModelValidationService validationService,
            IMapper mapper,
             IValidaterUser validateUser)
        {
            _jobService = jobService;
            _userService = userService;
            _validationService = validationService;
            _mapper = mapper;
            _validateUser = validateUser;
        }


        [Authorize(Roles = "Исполнитель,Заказчик")]
        public async Task<ActionResult> Profile(int? userId)
        {
            if (userId == null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    var user = await _userService.FindUserByEmail(User.Identity.Name);
                    var checkUser = User.FindFirstValue(ClaimsIdentity.DefaultNameClaimType); //нейминг checkUser
                    if (Equals(user.Email, checkUser))
                    {
                        var myprofile = await GetProfile(user.Id);
                        return View(myprofile);
                    }
                }
            }
            var profile = await GetProfile(userId.Value);
            return View(profile);
        }


        /// <summary>
        /// View edit profile
        /// </summary>
        /// <returns>View Profile/Edit</returns>
        public async Task<ActionResult> Edit()
        {
            var user = await _userService.FindUserByEmail(User.Identity.Name);
            var mapUserViewModel = _mapper.Map<UserDTO, ProfileEditViewModel>(user);
            return View(mapUserViewModel);
        }

        /// <summary>
        /// Request to edit user data
        /// </summary>
        /// <param name="model">model type of ProfileEditViewModel</param>
        /// <returns>View Profile/Profike</returns>
        [Authorize(Roles = "Исполнитель,Заказчик")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProfileEditViewModel model)
        {
            var validate = await _validateUser.ValidateEditUser(model.Phone);
            if (ModelState.IsValid)
            {
                if (validate)
                {
                    var modelDTO = _mapper.Map<ProfileEditViewModel, UserProfileEditDTO>(model);
                    var user = await _userService.FindUserByEmail(User.Identity.Name);
                    await _userService.Update(modelDTO, user);
                    var newuser = await _userService.FindUserByEmail(User.Identity.Name);
                    await Authenticate(newuser);
                    return RedirectToAction(nameof(Profile));
                }
            }
            ModelState.AddModelError("", "Такой номер телефона уже используется в системе");
            return View(model);

        }

        /// <summary>
        /// Logout user
        /// </summary>
        /// <returns>View Account/User</returns>
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Account");
        }

        private async Task Authenticate(UserDTO user)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, user.Email),
                new Claim(ClaimsIdentity.DefaultRoleClaimType, user.Role.DisplayName())
            };
            ClaimsIdentity id = new ClaimsIdentity(claims, "AuthCookie", ClaimsIdentity.DefaultNameClaimType,
                ClaimsIdentity.DefaultRoleClaimType);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        private async Task<ProfileViewModel> GetProfile()
        {
            var userDTO = await _userService.FindUserByEmail(User.Identity.Name);
            var map = _mapper.Map<UserDTO, ProfileViewModel>(userDTO);
            map.Role = userDTO.Role;
            map.City = userDTO.City;
            return map;
        }

        private async Task<ProfileViewModel> GetProfile(int userId)
        {
            var userDTO = await _userService.FindUserById(userId);
            var map = _mapper.Map<UserDTO, ProfileViewModel>(userDTO);
            map.Role = userDTO.Role;
            map.City = userDTO.City;
            return map;
        }
    }
}

FreelanceService/Views/Home/Executors.cshtml
@model PaginatedListModel<FreelanceService.Web.Models.UserExecutorViewModel>
@using FreelanceService.Common.Extensions
<div class="panel-header panel-header-sm">
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Исполнители</h5>
                </div>
                <div class="card-body">
                    <form asp-action="Executors" method="get">
                        <div class="form-actions no-color">
                            <p>
                                Поиск по имени: <input type="text" class="form-control search-input" name="SearchString" value="@ViewData["currentFilter"]" />
                                <input type="submit" value="Поиск" class="btn btn-sm btn-default" /> |
                                <a asp-action="Executors">Сбросить</a>
                            </p>
                        </div>
                    </form>

                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    <p>Исполнитель</p>
                                </th>
                                <th>
                                    <p> Место проживания</p>
                                </th>
                                <th>
                                    <a asp-action="Executors" asp-route-sortOrder="@ViewData["RatingSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Рейтинг</a>
                                </th>
                                <th>
                                    <a asp-action="Executors" asp-route-sortOrder="@ViewData["RegistrationDateTimeSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Дата регистрации</a>
                                </th>
                                <th>
                                    <p> Действия</p>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>

                                    <td>
                                        <p>@item.FirstName @item.LastName</p>
                                    </td>
                                    <td>
                                        <p>@item.City.DisplayName()</p>
                                    </td>
                                    <td>
                                        <p>@item.Rating</p>
                                    </td>
                                    <td>
                                        <p>@item.RegistrationDateTime.ToString("d")</p>
                                    </td>
                                    <td>
                                        <a asp-controller="Profile" asp-action="Profile" asp-route-userId="@item.Id" title="Посмотреть" type="button" rel="tooltip" class="btn btn-success btn-sm btn-icon">
                                            <i class="now-ui-icons ui-2_settings-90"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @await Html.PartialAsync("Partials/_Paginator",
                        new PaginatorViewModel
                        {
                            Action = "Index",
                            Controller = "Home",
                            Properties =
                                new
                                {
                                    sortOrder = @ViewData["CurrentSort"],
                                    currentFilter = @ViewData["CurrentFilter"]
                                },
                            Url = Url,
                            Paginator = Model
                        })
                </div>
            </div>
        </div>
    </div>
</div>

FreelanceService/Views/Home/Index.cshtml
@model PaginatedListModel<FreelanceService.Web.Models.JobViewModel>
@using FreelanceService.Common.Extensions

@{
    ViewData["Title"] = "Index";
    //Layout = "../Shared/_Layout.cshtml";
}

<div class="panel-header panel-header-sm">
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Заказы</h5>
                </div>
                <div class="card-body">
                    <form asp-action="Index" method="get">
                        <div class="form-actions no-color">
                            <p>
                                Поиск по имени: <input type="text" class="form-control search-input" name="SearchString" value="@ViewData["currentFilter"]" />
                                <input type="submit" value="Поиск" class="btn btn-sm btn-default" /> |
                                <a asp-action="Index">Сбросить</a>
                            </p>
                        </div>
                    </form>

                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Имя</a>
                                </th>
                                <th>
                                    <p>Описание</p>
                                </th>
                                <th>
                                    <p>Местоположение</p>
                                </th>
                                <th>
                                    <p>Дата окончания</p>
                                </th>
                                <th>
                                    <p>Категория</p>
                                </th>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["PriceSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Цена</a>
                                </th>
                                <th>
                                    <p>Действия</p>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @item.Name
                                </td>
                                <td>
                                    <p itemprop="text" >@item.Description</p> 
                                </td>
                                <td>
                                   <p> @item.City.DisplayName()</p>
                                </td>
                                <td>
                                    <p>@item.FinishedDateTime.ToString("d")</p>
                                </td>
                                <td>
                                   <p> @item.CategoryName</p>
                                </td>
                                @if (item.Price != null)
                                {
                                    <td>
                                       <p> @item.Price</p>
                                    </td>
                                }
                                else
                                {
                                    <td>
                                       <p> По договоренности</p>
                                    </td>
                                }
                            <td>
                                <a asp-controller="Job" asp-action="Job" asp-route-id="@item.Id" title="Посмотреть" type="button" rel="tooltip" class="btn btn-success btn-sm btn-icon">
                                    <i class="now-ui-icons ui-2_settings-90"></i>
                                </a>
                               
                            </td>
                            </tr>
                            }
                        </tbody>
                    </table>

                    @await Html.PartialAsync("Partials/_Paginator",
                        new PaginatorViewModel
                        {
                            Action = "Index",
                            Controller = "Home",
                            Properties =
                                new
                                {
                                    sortOrder = @ViewData["CurrentSort"],
                                    currentFilter = @ViewData["CurrentFilter"]
                                },
                            Url = Url,
                            Paginator = Model
                        })
                </div>
            </div>
        </div>
    </div>
</div>