FreelanceService/Models/ResponseDetailsViewModel.cs
using FreelanceService.Common.Enum;
using System;
using System.ComponentModel.DataAnnotations;

namespace FreelanceService.Web.Models
{
    public class ResponseDetailsViewModel
    {
        public int ResponseId { get; set; }
        [Display(Name = "Номер задания")]
        public int JobId { get; set; }

        [Display(Name = "Категория")]
        public int CategoryId { get; set; }

        [Display(Name = "Категория")]
        public string CategoryName { get; set; }

        [Display(Name = "Описание")]
        public string Description { get; set; }

        [Display(Name = "Дата отклика")]
        public DateTime ResponseDateTime { get; set; }

        [Display(Name = "Цена")]
        public decimal Price { get; set; }

        [Display(Name="Название работы")]
        public string NameJob { get; set; }

        [Display(Name = "Статус работы")]
        public JobStatusEnum StatusJob { get; set; }
    }
}

FreelanceService/Controllers/ExecutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FreelanceService.BLL.DTO;
using FreelanceService.BLL.Interfaces;
using FreelanceService.Common.Enum;
using FreelanceService.Web.Models;
using FreelanceService.Web.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FreelanceService.Web.Controllers
{
    public class ExecutorController : Controller
    {
        IUserService _userService;
        IJobService _jobService;
        IResponseService _responseService;
        ICategoryService _categoryService;
        IMapper _mapper;


        IViewModelValidationService _validationService;

        /// <summary>
        /// Dependency Injection for jobService and userService
        /// </summary>
        /// <param name="jobService"></param>
        /// <param name="userService"></param>
        public ExecutorController(
            IJobService jobService,
            IUserService userService,
            IViewModelValidationService validationService,
            IResponseService responseService,
            IMapper mapper,
            ICategoryService categoryService)
        {
            _jobService = jobService;
            _userService = userService;
            _validationService = validationService;
            _responseService = responseService;
            _mapper = mapper;
            _categoryService = categoryService;
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> MyResponses()
        {
            var user = await _userService.FindUserByEmail(User.Identity.Name);
            var responsesOfExecutor = await _responseService.FindResponseByUserExecutorId(user.Id);
            var mapResponseOfExecutor = _mapper.Map<IEnumerable<ResponseDTO>, IEnumerable<ResponseListOfExecutors>>(responsesOfExecutor);
            return View(mapResponseOfExecutor);
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> ResponseDetails(int responseId)
        {
            var responseOfExecutor = await _responseService.FindResponseById(responseId);
            var mapResponseDetails = _mapper.Map<ResponseDTO, ResponseDetailsViewModel>(responseOfExecutor);
            var job = await _jobService.FindJobById(mapResponseDetails.JobId);
            mapResponseDetails.CategoryId = job.CategoryId;
            var categoryDto = await _categoryService.FindCategoryById(mapResponseDetails.CategoryId);
           
            mapResponseDetails.CategoryName = categoryDto.Name;
            mapResponseDetails.StatusJob = job.Status;
            return View(mapResponseDetails);
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<ViewResult> EditResponse(int responseId)
        {
            var job = await _responseService.FindResponseById(responseId);
            var mapJob = _mapper.Map<ResponseDTO, ResponseEditViewModel>(job);
            return View(mapJob);
        }

        [HttpPost]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> EditResponse(ResponseEditViewModel model)
        {
            var responseDTO = await _responseService.FindResponseById(model.Id);
            var mapJob = _mapper.Map<ResponseEditViewModel, ResponseDTO>(model);
            responseDTO.Price = mapJob.Price; //вынести на bll
            responseDTO.Description = mapJob.Description;
            await _responseService.Update(responseDTO);

            return RedirectToAction("MyResponses");
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> SendForVerification(int jobId)
        {
            return View(jobId);
        }

        [HttpPost]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> ConfirmSendForVerification(int jobId)
        {
            var statusCode = (int)JobStatusEnum.WaitingForConfirmation;
            await _jobService.UpdateStatusJob(jobId, statusCode);
            return RedirectToAction("MyResponses");
        }

        [HttpGet]
        [Authorize(Roles = "Исполнитель")]
        public async Task<IActionResult> CancelResponse(int jobId)
        {
            var user = await _userService.FindUserByEmail(User.Identity.Name);  //перенести логику в responsesrvice
            var response = await _responseService.FindResponseByIdExecutorAndJobId(user.Id, jobId);
            await _responseService.Remove(response.Id);
            return RedirectToAction("MyResponses");
        }
    }
}

FreelanceService/Views/Executor/EditResponse.cshtml
@model FreelanceService.Web.Models.ResponseEditViewModel
@{
    ViewData["Title"] = "EditResponse";
}

<div class="panel-header panel-header-sm">
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Редактировать отзыв</h5>
                </div>
                <div class="card-body">
                    <form method="post" action="MyJobs/EditJob">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <input type="hidden" asp-for="Id" class="form-control" value="@Model.Id">
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea  asp-for="Description" class="form-control" value="@Model.Description" ></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div>
                            <label asp-for="Price"></label>
                            <input type="number" asp-for="Price" class="form-control" value="@Model.Price" min="0" placeholder="0.00">
                            <span asp-validation-for="Price" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Сохранить" asp-controller="Executor" asp-action="EditResponse" class="btn  btn-outline-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

FreelanceService/Views/Executor/MyResponses.cshtml
@model IEnumerable<FreelanceService.Web.Models.ResponseListOfExecutors>
<div class="panel-header panel-header-sm">
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Мои отклики</h5>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    <label class="control-label">Номер заказа</label>
                                </th>
                                <th>
                                    <label class="control-label">Время отклика</label>
                                </th>
                                <th>
                                    <label class="control-label">Описание</label>
                                </th>
                                <th>
                                    <label class="control-label">Цена</label>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    <p>@item.JobId</p>
                                </td>
                                <td>
                                    <p>@item.ResponseDateTime</p>
                                </td>
                                <td>
                                    <p>@item.Description</p>
                                </td>
                                <td>
                                    <p>@item.Price</p>
                                </td>
                                <td>
                                    <p></p>
                                </td>
                                <td>
                                    <a asp-controller="Executor" asp-action="ResponseDetails" asp-route-responseId="@item.ResponseId">Посмотреть</a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

FreelanceService/Views/Executor/ResponseDetails.cshtml
@model FreelanceService.Web.Models.ResponseDetailsViewModel
@using FreelanceService.Common.Extensions
@using FreelanceService.Common.Enum
<div class="panel-header panel-header-sm">
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Детали отклика</h5>
                </div>
                <div class="card-body">
                    <div><label asp-for="JobId" class="control-label"></label> <label> : @Model.JobId</label></div>
                    <div><label asp-for="NameJob" class="control-label"></label> <label> : @Model.NameJob</label></div>
                    <div><label asp-for="Description" class="control-label"></label> <label> : @Model.Description</label></div>
                    <div><label asp-for="Price" class="control-label"></label> <label> : @Model.Price</label></div>
                    <div><label asp-for="ResponseDateTime" class="control-label"></label> <label> : @Model.ResponseDateTime</label></div>
                    <div><label asp-for="CategoryName" class="control-label"></label> <label> : @Model.CategoryName</label></div>
                    <div><label asp-for="StatusJob" class="control-label"></label> <label> : @Model.StatusJob.DisplayName()</label></div>
                    <div>
                        @if (Model.StatusJob == JobStatusEnum.Published || Model.StatusJob == JobStatusEnum.Response)
                        {
                            <a asp-action="EditResponse" asp-controller="Executor" asp-route-responseId="@Model.ResponseId"> Редактировать Отклик</a>
                        }
                        @if (Model.StatusJob == JobStatusEnum.Deal || Model.StatusJob == JobStatusEnum.Response)
                        {
                            <a asp-action="CancelResponse" asp-controller="Executor" asp-route-jobId="@Model.JobId"> Отказаться от заказа</a>
                        }
                        @if (Model.StatusJob == JobStatusEnum.Deal)
                        {
                        <a asp-action="SendForVerification" asp-controller="Executor" asp-route-jobId="@Model.JobId"> Заказ выполнен</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FreelanceService/Views/Executor/SendForVerification.cshtml
@model int
@{
    ViewBag.Title = "Delete";
}
<div class="panel-header panel-header-sm">
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Запрос на подтверждение</h5>
                </div>
                <div class="card-body">
                    <form method="post">
                        <h2>Отправить запрос на подвтерждение выполненного заказа?</h2>
                        <input type="submit" class="btn  btn-outline-success" value="Подтвердить" asp-controller="Executor" asp-action="ConfirmSendForVerification" asp-route-jobId="@Model" />
                        <input type="submit" class="btn  btn-secondary" value="Отмена" asp-controller="Executor" asp-action="MyResponses" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>